let cities = [
    {
        id: 1,
        label: 'Tel-Aviv',
        name: 'tel_aviv',
        description: 'Wonderful city',
        country: 'Israel',
        image: "images/cities/tel_aviv.jpg",
        type: "city",
    },
    {
        id: 2,
        label: 'New York',
        name: 'new_york',
        description: 'Wonderful city',
        country: 'United State',
        image: "images/cities/new_york.jpg",
        type: "city",
    },
    {
        id: 3,
        label: 'New Delhi',
        name: 'new_delhi',
        description: 'India',
        country: 'United State',
        image: "images/cities/new_delhi.jpg",
        type: "city",
    },
    {
        id: 4,
        label: 'Barcelona',
        name: 'barcelona',
        description: 'Wonderful city',
        country: 'Spain',
        image: "images/cities/barcelona.jpg",
        type: "city",
    },
    {
        id: 5,
        label: 'Madrid',
        name: 'madrid',
        description: 'Wonderful city',
        country: 'Spain',
        image: "images/cities/madrid.jpg",
        type: "city",
    },
    {
        id: 6,
        label: 'London',
        name: 'london',
        description: 'Wonderful city',
        country: 'United Kingdom',
        image: "images/cities/london.jpg",
        type: "city",
    },
    {
        id: 7,
        label: 'Liverpool',
        name: 'liverpool',
        description: 'Wonderful city',
        country: 'United Kingdom',
        image: "images/cities/liverpool.jpg",
        type: "city",
    },
    {
        id: 8,
        label: 'Babruysk',
        name: 'babruysk',
        description: 'Wonderful city',
        country: 'Belarus',
        image: "images/cities/babruysk.jpg",
        type: "city",
    },
    {
        id: 9,
        label: 'Bacău',
        name: 'bacău',
        description: 'Wonderful city',
        country: 'Romania',
        image: "images/cities/bacău.jpg",
        type: "city",
    },
    {
        id: 10,
        label: 'Dublin',
        name: 'dublin',
        description: 'Wonderful city',
        country: 'Irland',
        image: "images/cities/dublin.jpg",
        type: "city",
    },
    {
        id: 11,
        label: 'Chicago',
        name: 'chicago',
        description: 'Wonderful city',
        country: 'United State',
        image: "images/cities/chicago.jpg",
        type: "city",
    },
    {
        id: 12,
        label: 'Rio de Janeiro',
        name: 'rio_de_janeiro',
        description: 'Wonderful city',
        country: 'Brazil',
        image: "images/cities/rio_de_janeiro.png",
        type: "city",
    },
    {
        id: 13,
        label: 'Sau Paulo',
        name: 'sau_paulo',
        description: 'Wonderful city',
        country: 'Brazil',
        image: "images/cities/sau_paulo.jpg",
        type: "city",
    },
    {
        id: 14,
        label: 'Paris',
        name: 'paris',
        description: 'Wonderful city',
        country: 'France',
        image: "images/cities/paris.jpg",
        type: "city",
    },
    {
        id: 15,
        label: 'Roma',
        name: 'roma',
        description: 'Wonderful city',
        country: 'Italy',
        image: "images/cities/roma.jpg",
        type: "city",
    },
    {
        id: 16,
        label: 'Sidney',
        name: 'sidney',
        description: 'Wonderful city',
        country: 'Australia',
        image: "images/cities/sidney.jpg",
        type: "city",
    },
    {
        id: 17,
        label: 'Tokyo',
        name: 'tokyo',
        description: 'Wonderful city',
        country: 'Japan',
        image: "images/cities/tokyo.jpg",
        type: "city",
    },
    {
        id: 18,
        label: 'Moscow',
        name: 'moscow',
        description: 'Wonderful city',
        country: 'Russia',
        image: "images/cities/moscow.jpg",
        type: "city",
    },
    {
        id: 19,
        label: 'Mexico City',
        name: 'mexico_city',
        description: 'Wonderful city',
        country: 'Mexico',
        image: "images/cities/mexico_city.jpg",
        type: "city",
    },
    {
        id: 20,
        label: 'Hong Kong',
        name: 'hong_Kong',
        description: 'Wonderful city',
        country: 'China',
        image: "images/cities/hong_Kong.jpg",
        type: "city",
    },
    {
        id: 21,
        label: 'Berlin',
        name: 'berlin',
        description: 'Wonderful city',
        country: 'Germany',
        image: "images/cities/berlin.jpg",
        type: "city",
    }
];

export {cities};